/** Prepare the public-domain Mutopia MIDI and Cadance manifest. */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import midiPackage from "@tonejs/midi";
import { parseMidi } from "../src/core/import";
import { measures } from "../src/core/loops";
import { songFingerprint } from "../src/core/quests";

const { Midi } = midiPackage;
const id = "chopin-waterfall-op-10-no-1";
const sourcePath = "public/pieces/chopin-waterfall.mid";
const outputPath = `public/pieces/${id}.mid`;
const source = readFileSync(sourcePath);
const midi = new Midi(source);
if (midi.tracks.length < 2) throw new Error("Waterfall MIDI needs upper and lower written-staff tracks.");
midi.name = "Frédéric Chopin · Étude Op. 10 No. 1 (Waterfall)";
midi.tracks[0].name = "Upper written staff";
midi.tracks[1].name = "Lower written staff";
const preparedBytes = midi.toArray();
writeFileSync(outputPath, preparedBytes);
const buffer = preparedBytes.buffer.slice(preparedBytes.byteOffset, preparedBytes.byteOffset + preparedBytes.byteLength) as ArrayBuffer;
const song = parseMidi(buffer, "Chopin · Étude Op. 10 No. 1 (Waterfall)");
song.id = id;
song.title = "Chopin · Étude Op. 10 No. 1 (Waterfall)";
song.composer = "Frédéric Chopin";
song.explanation = "A C-major étude built from continuous right-hand arpeggios over a sustained left-hand harmonic foundation. The Mutopia/Peters score and MIDI preserve the source staves; use Parts & accompaniment to adapt redistributions for your own hand span.";
song.ppq = 384;
song.meters = [{ tick: 0, numerator: 4, denominator: 4 }];
song.keys = [{ tick: 0, key: "C", scale: "major" }];
song.trackNames = ["Upper written staff", "Lower written staff"];
song.roleSource = "score";
song.scoreUrl = `/pieces/${id}.pdf`;
song.sourceUrl = "https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=914";
song.attribution = "Mutopia Project 914, Etüde C-Dur, F.F. Chopin Opus 10 No. 1; Peters/Herrmann Scholtz (1900b), typeset by Roland Goretzki. Public domain.";
song.notes = song.notes.map((note, index) => ({ ...note, id: `${id}:${index}`, hand: note.track === 0 ? ("right" as const) : ("left" as const) }));
const barCount = measures(song).length;
if (song.notes.length !== 1337 || barCount !== 79) throw new Error(`Unexpected shape: ${song.notes.length} notes / ${barCount} bars.`);
const { original: _original, ...data } = song;
writeFileSync(`src/core/${id}.json`, `${JSON.stringify({ ...data, originalBytes: [...preparedBytes] }, null, 2)}\n`);
console.log(JSON.stringify({ id, sourceSha256: createHash("sha256").update(source).digest("hex"), preparedSha256: createHash("sha256").update(preparedBytes).digest("hex"), notes: song.notes.length, bars: barCount, duration: song.duration, fingerprint: await songFingerprint(song) }, null, 2));
