import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import midiPackage from "@tonejs/midi";
import { parseMidi } from "../src/core/import";
import { measures } from "../src/core/loops";
import { songFingerprint } from "../src/core/quests";
const { Midi } = midiPackage;
const id = "mozart-piano-sonata-k545-i";
const source = readFileSync("public/pieces/mozart-k545-i.mid");
const midi = new Midi(source);
midi.name = "Wolfgang Amadeus Mozart · Piano Sonata No. 16 in C major, K. 545 · I. Allegro";
midi.tracks[0].name = "Upper written staff";
midi.tracks[1].name = "Lower written staff";
const bytes = midi.toArray();
writeFileSync(`public/pieces/${id}.mid`, bytes);
const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
const song = parseMidi(buffer, "Mozart · Piano Sonata K. 545 · I. Allegro");
song.id=id; song.title="Mozart · Piano Sonata No. 16 in C major, K. 545 · I. Allegro"; song.composer="Wolfgang Amadeus Mozart";
song.explanation="Mozart’s C-major Sonata facile opens with a clear Allegro in 4/4. Its bright C-major home and balanced phrases make it ideal for practicing articulation, repeated accompaniment patterns, and clean classical voicing.";
song.ppq=384; song.meters=[{tick:0,numerator:4,denominator:4}]; song.keys=[{tick:0,key:"C",scale:"major"}]; song.trackNames=["Upper written staff","Lower written staff"]; song.roleSource="score";
song.scoreUrl=`/pieces/${id}.pdf`; song.sourceUrl="https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=998"; song.attribution="Mutopia Project 998, Sonata Facile first movement, W. A. Mozart K. 545, typeset by Alejandro Sierra from IMSLP; Creative Commons Attribution-ShareAlike 3.0.";
song.notes=song.notes.map((n,i)=>({...n,id:`${id}:${i}`,hand:n.track===0?"right":"left"}));
const bars=measures(song).length; if(song.notes.length!==1288||bars!==73) throw Error(`Unexpected shape ${song.notes.length}/${bars}`);
const {original: _original,...data}=song; writeFileSync(`src/core/${id}.json`,JSON.stringify({...data,originalBytes:[...bytes]},null,2)+"\n");
console.log(JSON.stringify({id,notes:song.notes.length,bars,duration:song.duration,sourceSha256:createHash("sha256").update(source).digest("hex"),fingerprint:await songFingerprint(song)},null,2));
