import {writeFileSync} from "node:fs";
import data from "../src/core/mozart-piano-sonata-k545-i.json";
import type {Song} from "../src/core/model";
import {measures} from "../src/core/loops";
import {questTargets,readPracticePlan,songFingerprint,type PracticePlan} from "../src/core/quests";
const song=data as unknown as Song; const sections:[number,number,string][]=[[1,16,"Exposition · opening theme"],[17,32,"Exposition · transition and second theme"],[33,48,"Development · sequences"],[49,64,"Recapitulation · return to C major"],[65,73,"Coda · closing cadence"]];
const plan:PracticePlan={version:1,id:"mozart-piano-sonata-k545-i-v1",title:"K. 545 I · open practice route",song:{title:song.title,fingerprint:await songFingerprint(song)},repetitions:10,counting:"total",quests:[]};
for(const [sf,st,section] of sections)for(let from=sf;from<=st;from+=2){const through=Math.min(from+1,st);const base={section,fromBar:from,throughBar:through,focus:"all" as const,mode:"wait" as const,speed:.6,instruction:"Use a light, even classical touch. Keep the melody singing above the accompaniment and release repeated figures cleanly."};for(const hand of ["right","left","both"] as const){const q={...base,id:`bars-${from}-${through}-${hand}`,title:`Bars ${from}–${through} · ${hand==="both"?"Both hands":hand==="right"?"Right hand":"Left hand"}`,hand};if(questTargets(song,q).length)plan.quests.push(q)}if(from>sf&&through-sf+1<=10){const q={...base,id:`review-${sf}-${through}`,title:`Bars ${sf}–${through} · Section review`,fromBar:sf,hand:"both" as const,repetitions:5};if(questTargets(song,q).length)plan.quests.push(q)}}
const md=`# ${song.title} practice route\n\nAll checkpoints are unlocked. Choose any two-bar passage, then connect short reviews when ready.\n\n\`\`\`cadance-plan\n${JSON.stringify(plan,null,2)}\n\`\`\`\n`;await readPracticePlan(md,song);writeFileSync("public/plans/mozart-piano-sonata-k545-i.md",md);console.log(`${plan.quests.length} validated quests covering ${measures(song).length} bars`);
